export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER = 'DELETE_USER';


export const OPEN_CREATE_USER_DIALOG = 'OPEN_CREATE_USER_DIALOG';
export const OPEN_UPDATE_USER_DIALOG = 'OPEN_UPDATE_USER_DIALOG';
export const OPEN_DELETE_USER_DIALOG = 'OPEN_DELETE_USER_DIALOG';
export const CLOSE_ANY_DIALOG = 'CLOSE_ANY_DIALOG';
